
/* ============================================= */
/* == This file was generated by generate.ps1 == */
/* ==              DO NOT MODIFY              == */
/* ============================================= */


#ifndef __TRACY_SERVER_API_HPP__
#define __TRACY_SERVER_API_HPP__

#pragma once


#ifdef TRACY_ENABLE

#include "../public/TracyFeatureDefines.h"


#if defined( TRACY_HAS_SERVER_API_SUPPORT )


#   if defined(_WIN32)
#      pragma push_macro( "NOMINMAX" )
#      pragma push_macro( "WIN32_LEAN_AND_MEAN" )
#      if !defined( NOMINMAX )
#          define NOMINMAX
#      endif // if !defined( NOMINMAX )
#      if !defined( WIN32_LEAN_AND_MEAN )
#          define WIN32_LEAN_AND_MEAN
#      endif // if !defined( WIN32_LEAN_AND_MEAN )
#      pragma warning( push, 1 )
#      pragma warning( disable: 5262 )
#   endif // if defined(_WIN32)


#   define TRACY_OVERRIDE_PROCESS_FORCE_INCLUDES 1
#   define TRACY_NO_CAPSTONE 1
#   define TRACY_NO_EXCEPTIONS 1


#   if !defined(_WIN32)
#       define NO_PARALLEL_SORT 1
#   endif // if !defined(_WIN32)

#   if TRACY_OVERRIDE_PROCESS_FORCE_INCLUDES
#       define tracy_force_inline_process
#   endif // if TRACY_OVERRIDE_PROCESS_FORCE_INCLUDES

#   define __TRACYSORT_HPP__
#   include "../server/tracy_pdqsort.h"

    namespace ppqsort {

    namespace execution {
    class sequenced_policy {};
    class parallel_policy {};
    class sequenced_policy_force_branchless {};
    class parallel_policy_force_branchless {};
    inline constexpr sequenced_policy seq{};
    inline constexpr parallel_policy par{};
    inline constexpr sequenced_policy_force_branchless seq_force_branchless{};
    inline constexpr parallel_policy_force_branchless par_force_branchless{};
    template<typename T, typename U>
    inline constexpr bool _is_same_decay_v = std::is_same_v<std::decay_t<T>, std::decay_t<U>>;
    } // namespace execution

    template <typename ExecutionPolicy, typename RandomIt>
    void sort( ExecutionPolicy&& policy, RandomIt begin, RandomIt end ) {
       ::tracy::pdqsort_branchless( begin, end );
    }
    template <typename ExecutionPolicy, typename RandomIt, typename Compare>
    void sort( ExecutionPolicy&& policy, RandomIt begin, RandomIt end, Compare comp ) {
        ::tracy::pdqsort_branchless( begin, end, comp );
    }
    } // namespace ppqsort

#   include "../server/TracyCharUtil.hpp"
#   include "../server/TracyEvent.hpp"
#   include "../server/TracyFileHeader.hpp"
#   include "../server/TracyFileMeta.hpp"
#   include "../server/TracyFileRead.hpp"
#   include "../server/TracyFileWrite.hpp"
#   include "../server/TracyMemory.hpp"
#   include "../server/TracyMmap.hpp"
#   include "../server/TracyPopcnt.hpp"
#   include "../server/TracyPrint.hpp"
#   include "../server/TracyShortPtr.hpp"
#   include "../server/TracySlab.hpp"
#   include "../server/TracySort.hpp"
#   include "../server/TracySortedVector.hpp"
#   include "../server/TracyStringDiscovery.hpp"
#   include "../server/TracySysUtil.hpp"
#   include "../server/TracyTaskDispatch.hpp"
#   include "../server/TracyTextureCompression.hpp"
#   include "../server/TracyThreadCompress.hpp"
#   include "../server/TracyVarArray.hpp"
#   include "../server/TracyVector.hpp"
#   include "../server/TracyWorker.hpp"
#   include "../server/GetMainWindowHandle.h"
#   include "../server/tracy_pdqsort.h"
#   include "../server/tracy_robin_hood.h"
#   include "../server/tracy_xxhash.h"


#   if defined(_WIN32)
#      pragma pop_macro( "NOMINMAX" )
#      pragma pop_macro( "WIN32_LEAN_AND_MEAN" )
#      pragma warning( pop )
#   endif // if defined(_WIN32)


#endif // if defined( TRACY_HAS_SERVER_API_SUPPORT )

#endif // ifdef TRACY_ENABLE
#endif // __TRACY_SERVER_API_HPP__
