
/* ============================================= */
/* == This file was generated by generate.ps1 == */
/* ==              DO NOT MODIFY              == */
/* ============================================= */


#ifdef TRACY_ENABLE


#include "../public/TracyFeatureDefines.h"


#if defined( TRACY_HAS_SERVER_API_SUPPORT )


#   include "TracyServerApiGen.hpp"

#   if defined(_WIN32)
#      pragma push_macro( "NOMINMAX" )
#      pragma push_macro( "WIN32_LEAN_AND_MEAN" )
#      if !defined( NOMINMAX )
#          define NOMINMAX
#      endif // if !defined( NOMINMAX )
#      if !defined( WIN32_LEAN_AND_MEAN )
#          define WIN32_LEAN_AND_MEAN
#      endif // if !defined( WIN32_LEAN_AND_MEAN )
#      pragma warning( push, 1 )
#      pragma warning( disable: 5262 )
#   endif // if defined(_WIN32)


//  IMPORTANT: This must be the opposite condition of the one found in TracyClient.cpp! (If you get link errors check it)
#   if !defined(TRACY_HAS_CALLSTACK) || !(TRACY_HAS_CALLSTACK == 2 || TRACY_HAS_CALLSTACK == 3 || TRACY_HAS_CALLSTACK == 4 || TRACY_HAS_CALLSTACK == 6)
#       include "../public/common/TracyStackFrames.cpp"
#   endif

#   include "../public/common/tracy_lz4hc.cpp"

#   define tracy_zdict_include_relative

#   include "../server/GetMainWindowHandle.cpp"
#   include "../server/TracyMemory.cpp"
#   include "../server/TracyMmap.cpp"
#   include "../server/TracyPrint.cpp"
#   include "../server/TracySysUtil.cpp"
#   include "../server/TracyTaskDispatch.cpp"
#   include "../server/TracyTextureCompression.cpp"
#   include "../server/TracyThreadCompress.cpp"
#   include "../server/TracyWorker.cpp"


#   if defined(_WIN32)
#      pragma pop_macro( "NOMINMAX" )
#      pragma pop_macro( "WIN32_LEAN_AND_MEAN" )
#      pragma warning( pop )
#   endif // if defined(_WIN32)


#endif // if defined( TRACY_HAS_SERVER_API_SUPPORT )

#endif // ifdef TRACY_ENABLE
